// ********RoostGPT********
/*
Test generated by RoostGPT for test aps-java-1 using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=getContextPath_4e3c5503cf
ROOST_METHOD_SIG_HASH=getContextPath_c9be1d65f0

""" 

Scenario 1: Test the method when the contextPath value is a valid string

Details:
  TestName: testContextPathForValidValue
  Description: In this test scenario, we are meant to check if the contextPath value is returned correctly when it's a valid string. 
Execution:
  Arrange: Assign the contextPath a valid string value.
  Act: Invoke the getContextPath() method.
  Assert: Use JUnit assertions to compare the actual result with the expected string value.
Validation:
  The assertion aims to verify that the getContextPath() returns the correct value. The expected result is significant in ensuring the correct context path is obtained when needed.

Scenario 2: Test the method when the contextPath value is an empty string

Details:
  TestName: testContextPathForEmptyString
  Description: This scenario checks to see if the getContextPath() returns an empty string when assigned such.
Execution:
  Arrange: Assign an empty string to the contextPath.
  Act: Call the getContextPath() method.
  Assert: Use JUnit assertions to check if the returned value is an empty string.
Validation:
  The assertion aims to verify that method returns an empty string when such is the set contextPath. This test is significant in verifying the method's correctness when dealing with empty strings.

Scenario 3: Test the method when the contextPath value is null.

Details:
  TestName: testContextPathForNullValue
  Description: This scenario checks if the getContextPath() method returns a null value when the contextPath is null.
Execution:
  Arrange: Assign null to the contextPath.
  Act: trigger the getContextPath() method.
  Assert: Use JUnit assertions to check if the returned value is null.
Validation:
  The assertion aims to verify that the getContextPath() method returns null when the contextPath is null. This test is significant in ensuring the method's correct handling of null values.
  
"""
*/

// ********RoostGPT********
package com.baeldung.jwt.config;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNull;

import org.junit.Before;
import org.junit.Test;

public class KeycloakServerPropertiesGetContextPathTest {
    
    private KeycloakServerProperties properties;

    @Before
    public void setUp() {
        properties = new KeycloakServerProperties();
    }

    @Test
    public void testContextPathForValidValue() {
        String expectedContextPath = "/auth";
        properties.setContextPath(expectedContextPath);

        String actualContextPath = properties.getContextPath();

        assertEquals(expectedContextPath, actualContextPath);
    }

    @Test
    public void testContextPathForEmptyString() {
        String expectedContextPath = "";
        properties.setContextPath(expectedContextPath);

        String actualContextPath = properties.getContextPath();

        assertEquals(expectedContextPath, actualContextPath);
    }

    @Test
    public void testContextPathForNullValue() {
        properties.setContextPath(null);

        String actualContextPath = properties.getContextPath();

        assertNull(actualContextPath);
    }
}
